version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: './Dockerfile'
    ports:
      - '9004:3000'
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN} # Discord bot token
      MONGODB_URI: ${MONGODB_URI} # 'mongodb://username:password@localhost:27017/forumfollow?authSource=admin&retryWrites=true&ssl=false'
      WEBHOOK_SHARD: ${WEBHOOK_SHARD} # Discord webhook url
      WEBHOOK_ERROR: ${WEBHOOK_ERROR} # Discord webhook url
      WEBHOOK_COMMAND: ${WEBHOOK_COMMAND} # Discord webhook url
      WEBHOOK_GUILD: ${WEBHOOK_GUILD} # Discord webhook url